apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-postgres-config
data:
  postgresql.conf: |
    wal_level = logical
    max_wal_senders = 10
    max_replication_slots = 10
    shared_buffers = 256MB
