apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-test-pub-pvc
  namespace: test-pub
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
